resources:
- name: automation
  type: git
  source:
    uri: https://github.com/saikrishna-tlsr/Automation-Training.git
    branch: master
    
  jobs:
  - name: vpc.tf
   plan:
    - get: automation
    - task: vpc.tf
    - file: automation/pipeline.yml
