resources:
- name: automation
  type: git
  source:
    uri: https://github.com/saikrishna-tlsr/Automation-Training.git
    branch: master
    
    jobs:
- name: vpc creation
  - get: automation
  - task: vpc creation
    file: automation/pipeline.yml
